# Regenerates inst/brand/tokens.json from `.islh_colours` in R/colours.R.
#
# Brand hexes used to live in three places that could silently drift: the R
# colour table, `_brand.yml`, and hardcoded constants in the Word reference-doc
# builder. `.islh_colours` is now the source; this script publishes it as a
# language-neutral token file that build_reference_docx.py reads, and
# tests/testthat/test-brand-tokens.R fails if the three disagree.
#
# Run with: Rscript data-raw/sync-brand-tokens.R

devtools::load_all(".", quiet = TRUE)

colours <- get(".islh_colours", envir = asNamespace("islhr"))
named <- get(".islh_brand_colours", envir = asNamespace("islhr"))

# Hand-rolled so the package needs no JSON dependency for a build-time script.
quote_string <- function(x) paste0('"', x, '"')

family_block <- function(family) {
  entry <- colours[[family]]
  pairs <- sprintf(
    '      "%s": %s',
    names(entry), quote_string(toupper(unname(entry)))
  )
  paste0(
    '    ', quote_string(family), ': {\n',
    paste(pairs, collapse = ',\n'), '\n    }'
  )
}

named_block <- paste(
  sprintf('    "%s": %s', names(named), quote_string(toupper(unname(named)))),
  collapse = ',\n'
)

json <- paste0(
  '{\n',
  '  "_comment": "Generated by data-raw/sync-brand-tokens.R from ',
  '.islh_colours in R/colours.R. Do not edit by hand.",\n',
  '  "families": {\n',
  paste(vapply(names(colours), family_block, character(1)), collapse = ',\n'),
  '\n  },\n',
  '  "named": {\n', named_block, '\n  }\n',
  '}\n'
)

path <- "inst/brand/tokens.json"
writeLines(json, path)
cat("wrote", path, "\n")
